name: CI/CD para Mi Página de Examen de Análisis

on:
  push:
    branches:
      - main  # Cambia a la rama en la que deseas que se active el Workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia la versión de Node.js si es necesario

      - name: Instalar dependencias
        run: npm install  # Asegúrate de que esto sea adecuado para tu proyecto

      - name: Construir y desplegar
        run: |
          npm run build  # Ejecuta cualquier comando necesario para construir tu proyecto
          # Ejemplo: npm run build o cualquier otro comando necesario para construir tu proyecto

      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages  # Rama en la que deseas desplegar tu página
          folder: .  # Carpeta desde la que deseas desplegar (en este caso, la raíz)

